name: Deploy docs site to Pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

defaults:
    run:
        shell: bash

jobs:
    # Build job
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 'latest'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install
              working-directory: docs/

            - name: Run check on yaasm
              run: npm install && npm run check

            - name: Build project
              run: npm run build
              working-directory: docs/

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: ./docs/build

    # Deployment job
    deploy:
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: production-files
                  path: ./docs/build
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './docs/build'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
